# Generated by Django 3.0.2 on 2020-05-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='backdrop',
            field=models.ImageField(blank=True, default='default-profile-pic.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='projects',
            field=models.ManyToManyField(to='projects.Project'),
        ),
        migrations.AddField(
            model_name='account',
            name='site',
            field=models.URLField(null=True),
        ),
    ]
